name: run-app-tests
run-name: ${{ github.actor }} is learning GitHub Actions
on: [pull_request, workflow_dispatch]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - run: yarn
      - run: yarn deploy-test
