name: Publish Package to npmjs

on:
  release:
    types: [published]
  push:
    branches:
      - main

concurrency:
  group: npm-publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.1"
          registry-url: "https://registry.npmjs.org"
          cache: 'yarn'

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: yarn-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.os }}-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Bump version (optional: patch, minor, or major)
        id: version
        run: |
          VERSION_TYPE="patch" # Can be "patch", "minor", or "major"
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: $CURRENT_VERSION"
          NEW_VERSION=$(npm version $VERSION_TYPE --no-git-tag-version)
          echo "New version: $NEW_VERSION"
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Build package
        run: yarn build

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > ~/.npmrc
          yarn publish --access public

      - name: Commit new version to package.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add package.json
          git commit -m "Bump version to ${{ env.VERSION }}"
          git push origin main
